// The Settings the meetings module reads, as one list of keys and one mapping,
// so the Server reads them in one query and a test maps defaultSettings.

import type { Settings } from "@monday/shared";
import type { MeetingSettings } from "./index.ts";

export const MEETING_SETTING_KEYS = [
  "meetings.enabled",
  "meetings.on_arrival",
  "meetings.lead_minutes",
  "meetings.slots",
  "meetings.slots_per_day",
  "meetings.lookahead_days",
  "meetings.busy_calendars",
  "meetings.parts_of_day",
  "meetings.offer.threshold",
  "meetings.schedule.threshold",
  "meetings.schedule.time_confidence",
  "meetings.suggest.threshold",
  "meetings.pick.threshold",
  "meetings.length_confidence",
  "meetings.recurring_threshold",
  "meetings.non_english",
  "meetings.llm_fallback",
  "meetings.proposals_max",
  "meetings.candidates_max",
  "meetings.state.newest_chars",
  "meetings.state.earlier_chars",
  "meetings.gate_words",
  "meetings.draft_prompt",
  "meetings.questions.asks_to_meet",
  "meetings.questions.owner_asked",
  "meetings.questions.proposes_time",
  "meetings.questions.recurring",
  "meetings.questions.length",
  "meetings.questions.zone",
  "meetings.questions.parts",
  "strings.meetings.draft.offer",
  "strings.meetings.draft.suggest",
  "strings.meetings.draft.accept",
  "strings.meetings.draft.slot",
  "strings.meetings.event_title",
  "calendar.time_zone",
  "calendar.day_start_hour",
  "calendar.day_end_hour",
  "calendar.work_days",
  "calendar.snap_minutes",
  "calendar.default_duration_minutes",
  "calendar.week_starts_monday",
] as const;

export type MeetingSettingValues = Pick<Settings, (typeof MEETING_SETTING_KEYS)[number]>;

export function meetingSettingsFrom(s: MeetingSettingValues): MeetingSettings {
  return {
    enabled: s["meetings.enabled"],
    onArrival: s["meetings.on_arrival"],
    llmFallback: s["meetings.llm_fallback"],
    proposalsMax: s["meetings.proposals_max"],
    candidatesMax: s["meetings.candidates_max"],
    newestChars: s["meetings.state.newest_chars"],
    earlierChars: s["meetings.state.earlier_chars"],
    gateWords: [...s["meetings.gate_words"]],
    busyCalendars: s["meetings.busy_calendars"],
    timeZone: s["calendar.time_zone"],
    questions: {
      asksToMeet: s["meetings.questions.asks_to_meet"],
      ownerAsked: s["meetings.questions.owner_asked"],
      proposesTime: s["meetings.questions.proposes_time"],
      recurring: s["meetings.questions.recurring"],
      length: s["meetings.questions.length"],
      zone: s["meetings.questions.zone"],
      parts: s["meetings.questions.parts"],
    },
    draft: {
      prompt: s["meetings.draft_prompt"],
      offer: s["strings.meetings.draft.offer"],
      suggest: s["strings.meetings.draft.suggest"],
      accept: s["strings.meetings.draft.accept"],
      slot: s["strings.meetings.draft.slot"],
    },
    titleFallback: s["strings.meetings.event_title"],
    plan: {
      offerThreshold: s["meetings.offer.threshold"],
      scheduleThreshold: s["meetings.schedule.threshold"],
      timeConfidence: s["meetings.schedule.time_confidence"],
      suggestThreshold: s["meetings.suggest.threshold"],
      pickThreshold: s["meetings.pick.threshold"],
      lengthConfidence: s["meetings.length_confidence"],
      recurringThreshold: s["meetings.recurring_threshold"],
      nonEnglish: s["meetings.non_english"],
      leadMinutes: s["meetings.lead_minutes"],
      slots: s["meetings.slots"],
      slotsPerDay: s["meetings.slots_per_day"],
      lookaheadDays: s["meetings.lookahead_days"],
      defaultLength: s["calendar.default_duration_minutes"],
      snapMinutes: s["calendar.snap_minutes"],
      work: {
        startHour: s["calendar.day_start_hour"],
        endHour: s["calendar.day_end_hour"],
        days: [...s["calendar.work_days"]],
      },
      weekStartsMonday: s["calendar.week_starts_monday"],
      partsOfDay: s["meetings.parts_of_day"],
    },
  };
}
